@php
$t = [
    'en' => [
        'subtitle' => 'Bill Summary',
        'date' => 'Date',
        'currency' => 'Currency',
        'items' => 'Items',
        'item' => 'Item',
        'qty' => 'Qty',
        'price' => 'Price',
        'total' => 'Total',
        'subtotal' => 'Subtotal',
        'grand_total' => 'Grand Total',
        'adjustments' => 'Extras',
        'participants' => 'Participants',
        'name' => 'Name',
        'share' => 'Share',
        'payer' => 'payer',
        'paid_by' => 'Paid by',
        'who_owes' => 'Who owes whom',
        'owes' => 'owes',
        'generated' => 'Generated by Chippin on',
        'adj_types' => [
            'tip' => 'Tips',
            'service' => 'Service fee',
            'tax' => 'Tax',
            'delivery' => 'Delivery',
            'discount' => 'Discount',
        ],
    ],
    'ru' => [
        'subtitle' => 'Итоги счёта',
        'date' => 'Дата',
        'currency' => 'Валюта',
        'items' => 'Позиции',
        'item' => 'Позиция',
        'qty' => 'Кол-во',
        'price' => 'Цена',
        'total' => 'Итого',
        'subtotal' => 'Подытог',
        'grand_total' => 'Итого',
        'adjustments' => 'Доп. сборы',
        'participants' => 'Участники',
        'name' => 'Имя',
        'share' => 'Доля',
        'payer' => 'оплатил',
        'paid_by' => 'Оплатил',
        'who_owes' => 'Кто кому должен',
        'owes' => 'должен',
        'generated' => 'Сгенерировано Chippin',
        'adj_types' => [
            'tip' => 'Чаевые',
            'service' => 'Обслуживание',
            'tax' => 'Налог',
            'delivery' => 'Доставка',
            'discount' => 'Скидка',
        ],
    ],
];
$l = $t[$lang] ?? $t['en'];
@endphp
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #333;
            margin: 40px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            font-size: 28px;
            color: #2563eb;
            margin: 0;
        }
        .header .subtitle {
            font-size: 14px;
            color: #666;
        }
        .bill-info {
            margin-bottom: 20px;
            padding: 15px;
            background: #f8fafc;
            border-radius: 5px;
        }
        .bill-info h2 {
            margin: 0 0 5px 0;
            font-size: 18px;
        }
        .bill-info p {
            margin: 3px 0;
            color: #555;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background: #2563eb;
            color: white;
            padding: 8px 12px;
            text-align: left;
            font-size: 11px;
        }
        td {
            padding: 8px 12px;
            border-bottom: 1px solid #e5e7eb;
        }
        tr:nth-child(even) {
            background: #f9fafb;
        }
        .text-right {
            text-align: right;
        }
        .total-row {
            font-weight: bold;
            background: #eff6ff !important;
        }
        .section-title {
            font-size: 14px;
            font-weight: bold;
            color: #2563eb;
            margin: 25px 0 10px 0;
            padding-bottom: 5px;
            border-bottom: 2px solid #2563eb;
        }
        .debt-item {
            padding: 8px 12px;
            margin: 5px 0;
            background: #fef3c7;
            border-left: 4px solid #f59e0b;
            border-radius: 3px;
        }
        .paid-by {
            padding: 10px 15px;
            background: #d1fae5;
            border-left: 4px solid #10b981;
            border-radius: 3px;
            margin-bottom: 15px;
        }
        .text-green {
            color: #10b981;
        }
        .text-red {
            color: #ef4444;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            color: #999;
            font-size: 10px;
            border-top: 1px solid #e5e7eb;
            padding-top: 15px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Chippin</h1>
        <div class="subtitle">{{ $l['subtitle'] }}</div>
    </div>

    <div class="bill-info">
        <h2>{{ $bill->name }}</h2>
        <p>{{ $l['date'] }}: {{ $bill->date->format('d.m.Y') }}</p>
        <p>{{ $l['currency'] }}: {{ $bill->currency }}</p>
    </div>

    <div class="section-title">{{ $l['items'] }}</div>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>{{ $l['item'] }}</th>
                <th class="text-right">{{ $l['qty'] }}</th>
                <th class="text-right">{{ $l['price'] }}</th>
                <th class="text-right">{{ $l['total'] }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($bill->items as $index => $item)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $item->name }}</td>
                <td class="text-right">{{ $item->quantity }}</td>
                <td class="text-right">{{ number_format($item->price_per_unit, 2) }}</td>
                <td class="text-right">{{ number_format($item->total, 2) }}</td>
            </tr>
            @endforeach
            <tr class="total-row">
                <td colspan="4" class="text-right">{{ count($adjustments) > 0 ? $l['subtotal'] : $l['total'] }}:</td>
                <td class="text-right">{{ number_format($subtotal, 2) }} {{ $bill->currency }}</td>
            </tr>
        </tbody>
    </table>

    @if(count($adjustments) > 0)
    <div class="section-title">{{ $l['adjustments'] }}</div>
    <table>
        <thead>
            <tr>
                <th>{{ $l['item'] }}</th>
                <th class="text-right">{{ $l['total'] }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($adjustments as $adj)
            @php
                $sign = $adj->type === 'discount' ? -1 : 1;
                $adjLabel = $l['adj_types'][$adj->type] ?? $adj->type;
                $pctLabel = $adj->calc_mode === 'percent' ? ' (' . $adj->value . '%)' : '';
                $prefix = $sign > 0 ? '+' : '−';
            @endphp
            <tr>
                <td>{{ $adjLabel }}{{ $pctLabel }}</td>
                <td class="text-right">{{ $prefix }}{{ number_format($adj->amount, 2) }} {{ $bill->currency }}</td>
            </tr>
            @endforeach
            <tr class="total-row">
                <td class="text-right">{{ $l['grand_total'] }}:</td>
                <td class="text-right">{{ number_format($grandTotal, 2) }} {{ $bill->currency }}</td>
            </tr>
        </tbody>
    </table>
    @endif

    <div class="section-title">{{ $l['participants'] }}</div>
    <table>
        <thead>
            <tr>
                <th>{{ $l['name'] }}</th>
                <th class="text-right">{{ $l['share'] }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($shares as $share)
            <tr>
                <td>{{ $share['name'] }}@if($share['participant_id'] === $bill->paid_by_participant_id) ({{ $l['payer'] }})@endif</td>
                <td class="text-right">{{ number_format($share['amount'], 2) }} {{ $bill->currency }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    @if($bill->paidByParticipant)
    <div class="paid-by">
        <strong>{{ $l['paid_by'] }}:</strong> {{ $bill->paidByParticipant->name }}
    </div>
    @endif

    @if(count($debts) > 0)
    <div class="section-title">{{ $l['who_owes'] }}</div>
    @foreach($debts as $debt)
    <div class="debt-item">
        <strong>{{ $debt['from'] }}</strong> {{ $l['owes'] }} <strong>{{ $debt['to'] }}</strong>: {{ number_format($debt['amount'], 2) }} {{ $bill->currency }}
    </div>
    @endforeach
    @endif

    <div class="footer">
        {{ $l['generated'] }} {{ now()->format('d.m.Y H:i') }}
    </div>
</body>
</html>
